services:
  relay:
    container_name: relay
    # image: ghcr.io/mroxso/nostr-rs-relay:latest
    image: nostr-rs-relay:local
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    user: 100:100
    volumes:
      - ./relay/data:/usr/src/app/db:Z
      - ./relay/config.toml:/usr/src/app/config.toml:ro,Z
  generator:
    container_name: generator
    build: ./generator
    ports:
      - 3000:3000
